-- ============================================================
--  AntiCheat - Silah Kontrolü (Client Side)
--
--  NOT: Silah tespiti ve kaldırma işlemi artık doğrudan
--  weapon_inventory_check.lua bypass modülünde yapılır.
--  (exports.ox_inventory:Search client export kullanılır)
--
--  Bu dosya ileride ek client-side handler'lar için ayrılmıştır.
-- ============================================================
